class CreatePlans < ActiveRecord::Migration[6.1]
  def change
    create_table :plans do |t|
      t.string :class1a1 , default: ""
      t.string :class1a2 , default: ""
      t.string :class1a3 , default: ""
      t.string :class1a4 , default: ""
      t.string :class1a5 , default: ""
      t.string :class1w1 , default: ""
      t.string :class1w2 , default: ""
      t.string :class1w3 , default: ""
      t.string :class1w4 , default: ""
      t.string :class1w5 , default: ""
      t.string :class1s1 , default: ""
      t.string :class1s2 , default: ""
      t.string :class1s3 , default: ""
      t.string :class1s4 , default: ""
      t.string :class1s5 , default: ""
      t.string :class1su1, default: ""
      t.string :class1su2, default: ""
      t.string :class1su3, default: ""
      t.string :class1su4, default: ""
      t.string :class1su5, default: ""
      t.string :class2a1 , default: ""
      t.string :class2a2 , default: ""
      t.string :class2a3 , default: ""
      t.string :class2a4 , default: ""
      t.string :class2a5 , default: ""
      t.string :class2w1 , default: ""
      t.string :class2w2 , default: ""
      t.string :class2w3 , default: ""
      t.string :class2w4 , default: ""
      t.string :class2w5 , default: ""
      t.string :class2s1 , default: ""
      t.string :class2s2 , default: ""
      t.string :class2s3 , default: ""
      t.string :class2s4 , default: ""
      t.string :class2s5 , default: ""
      t.string :class2su1, default: ""
      t.string :class2su2, default: ""
      t.string :class2su3, default: ""
      t.string :class2su4, default: ""
      t.string :class2su5, default: ""
      t.string :class3a1 , default: ""
      t.string :class3a2 , default: ""
      t.string :class3a3 , default: ""
      t.string :class3a4 , default: ""
      t.string :class3a5 , default: ""
      t.string :class3w1 , default: ""
      t.string :class3w2 , default: ""
      t.string :class3w3 , default: ""
      t.string :class3w4 , default: ""
      t.string :class3w5 , default: ""
      t.string :class3s1 , default: ""
      t.string :class3s2 , default: ""
      t.string :class3s3 , default: ""
      t.string :class3s4 , default: ""
      t.string :class3s5 , default: ""
      t.string :class3su1, default: ""
      t.string :class3su2, default: ""
      t.string :class3su3, default: ""
      t.string :class3su4, default: ""
      t.string :class3su5, default: ""
      t.string :class4a1 , default: ""
      t.string :class4a2 , default: ""
      t.string :class4a3 , default: ""
      t.string :class4a4 , default: ""
      t.string :class4a5 , default: ""
      t.string :class4w1 , default: ""
      t.string :class4w2 , default: ""
      t.string :class4w3 , default: ""
      t.string :class4w4 , default: ""
      t.string :class4w5 , default: ""
      t.string :class4s1 , default: ""
      t.string :class4s2 , default: ""
      t.string :class4s3 , default: ""
      t.string :class4s4 , default: ""
      t.string :class4s5 , default: ""
      
      t.timestamps
    end
  end
end
